-
  name: Ontap Cluster User
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap
  vars:
    ontap_use_https: true
    ontap_validate_certs: false
    login: &login
      state: present
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ ontap_use_https }}"
      validate_certs: "{{ ontap_validate_certs }}"
      vserver: cluster-ontap
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false
  pre_tasks:
  - include_vars:
      file: inventory.yml
      name: inventory
  - include_vars:
      file: helper.yml
      name: fw
  - set_fact:
      cust "{{ inventory | dict2items }}"

  tasks:   
   - name: Creating local user on cluster
     na_ontap_user:
      use_rest: always
      <<: *login
      name: "{{ item }}"
      application_dicts:
        - application: http
          authentication_methods: password
        - application: ssh
          authentication_methods: password
        - application: console
          authentication_methods: password
        - application: ontapi
          authentication_methods: password
        - application: service-processor
          authentication_methods: password
      role_name: admin
      set_password: test1234
     loop:
        - patrick
        - robin
        - ana
