---

-
  name: ONTAP Create User
  gather_facts: false
  hosts: cluster-ontap
  collections:
    - netapp.ontap
    
  tasks:
  
  - name: run ONTAP gather facts for vserver info
    netapp.ontap.na_ontap_rest_info:
       hostname: "1.2.3.4"
       username: "testuser"
       password: "test-password"
       https: true
       validate_certs: false
       use_rest: Always
       gather_subset:
        - svm/svms
