---

-
  name: ONTAP Create User
  gather_facts: false
  hosts: cluster-ontap
  collections:
    - netapp.ontap
    
  tasks:
  
  - name: run ONTAP gather facts for vserver info
    netapp.ontap.na_ontap_rest_info:
       hostname: "192.168.77.140"
       username: "admin"
       password: "Netapp1!"
       https: true
       validate_certs: false
       use_rest: Always
       gather_subset:
        - svm/svms
