---

-
  name: List Aggregate
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap
    
  tasks:
  
  - name: run ONTAP gather facts for aggregate info
    netapp.ontap.na_ontap_rest_info:
       hostname: "192.168.77.140"
       username: "admin"
       password: "Netapp1!"
       https: true
       validate_certs: false
       use_rest: Always
       gather_subset:
          - storage/aggregates
          - storage/volumes
