---

-
  name: ONTAP list aggregates
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap

  tasks:
  
    - import_playbook: list_aggregates.yml
    - import_playbook: clusters.yml
