---

-
  name: ONTAP Create User
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap
    
  tasks:
  
    - name: Create User
      netapp.ontap.na_ontap_user:
      state: present
      name: patrick
      applications: ssh,console
      authentication_method: password
      set_password: test123
      lock_user: True
      role_name: vsadmin
      vserver: cluster-ontap
      hostname: "192.168.77.140"
      username: "admin"
      password: "Netapp1!"
