#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        01_get_cluster_details.yml
# Author:       Adrian Bronder
# Date:         2020-03-18
# Description:  Get cluster information
#               with Ansible modules
#
# Modules:      na_ontap_info
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_info
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - global.yml
  collections:
    - netapp.ontap

tasks:
- name: Create User
      netapp.ontap.na_ontap_user:
        state: present
        name: SampleUser
        applications: ssh,console
        authentication_method: password
        set_password: apn1242183u1298u41
        lock_user: false
        role_name: admin
        vserver: cluster-home
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
