---
- name: ONTAP REST API
  become: false
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap

  tasks:
    - name: Create user
      netapp.ontap.na_ontap_user:
        state: present
        name: test123
        application_dicts:
          - application: http
            authentication_methods: password
          - application: ssh
            authentication_methods: password,publickey
        role_name: admin
        set_password: bobdole1234566
        vserver: cluster-home
        hostname: "192.168.20.140"
        username: "admin"
        password: "Netapp1!"
