---
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: false
  name: New User
  tasks:
  - name: Create
    netapp.ontap.na_ontap_user:
    state: present
    name: patrick
    applications: ssh,console
    authentication_method: password
    set_password: apn1242183u1298u41
    lock_user: True
    role_name: admin
    vserver: cluster-ontap
    hostname: 192.168.77.140
    username: admin
    password: Netapp1!
