---

- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: false
  name: New

tasks:
  
- name: Create User
      netapp.ontap.na_ontap_user:
        state: present
        name: SampleUser
        applications: ssh,console
        authentication_method: password
        set_password: apn1242183u1298u41
        lock_user: false
        role_name: admin
        vserver: cluster-home
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
