#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        01_get_cluster_details.yml
# Author:       Adrian Bronder
# Date:         2020-03-18
# Description:  Get cluster information
#               with Ansible modules
#
# Modules:      na_ontap_info
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_info
#
################################################################################

- 
  name: ONTAP REST API
  hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - global.yml
  collections:
    - netapp.ontap

tasks:
    - name: Create user
      netapp.ontap.na_ontap_user:
        state: present
        name: test123
        application_dicts:
          - application: http
            authentication_methods: password
          - application: ssh
            authentication_methods: password,publickey
        role_name: admin
        set_password: bobdole1234566
        vserver: cluster-home
        #hostname: "{{ hostname }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
