---
- name: ONTAP REST API
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    PRI_CLU: 192.168.77.140
    PRI_CLU_USER: admin
    PRI_CLU_PASS: Netapp1!
    vserver: cluster-ontap
  tasks:
    - #name: 'Create'
      netapp.ontap.na_ontap_user:
      state: present
      name: test123
      application_dicts:
        - application: http
          authentication_methods: password
        - application: ssh
          authentication_methods: password,publickey
      role_name: admin
      set_password: bobdole1234566
      vserver: "{{ vserver }}"
      hostname: "{{ PRI_CLU }}"
      username: "{{ PRI_CLU_USER }}"
      password: "{{ PRI_CLU_PASS }}"
