---

-
  name: Example Simple Playbook
  gather_facts: false
  hosts: local
  collections:
    - netapp.ontap
    
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: 192.168.77.140
      username: admin
      password: Netapp1!
     #hostname: '{{ clusters.cluster1.admin_ip }}'
      #username: '{{ clusters.cluster1.admin_username }}'
      #password: '{{ clusters.cluster1.admin_password }}'
      https: true
      validate_certs: false

 tasks:
   - name: Create User
     netapp.ontap.na_ontap_user:
     state: present
     name: SampleUser
     applications: ssh,console
     authentication_method: password
     set_password: apn1242183u1298u41
     lock_user: True
     role_name: vsadmin
     vserver: ansibleVServer
