---

-
  name: ONTAP Create User
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap
    
  tasks:
  
  - name: Create Adminuser
    netapp.ontap.na_ontap_user:
    state: present
    name: patrick
    applications: ssh,console
    authentication_method: password
    set_password: apn1242183u1298u41
    lock_user: True
    role_name: admin
    vserver: cluster-ontap
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
