---

-
  name: ONTAP Create User
  gather_facts: false
  hosts: cluster-ontap
  collections:
    - netapp.ontap
    
  tasks:
  
    - name: Create User
      netapp.ontap.na_ontap_user:
      state: present
      name: SampleUser
      applications: ssh,console
      authentication_method: password
      set_password: apn1242183u1298u41
      lock_user: True
      role_name: vsadmin
      vserver: ansibleVServer
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
