---

-
  name: "ONTAP CLI Commands"
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap

- name: run ontap cli command
  netapp.ontap.na_ontap_command:
    hostname: "{{ hostname }}"
    username: "{{ admin username }}"
    password: "{{ admin password }}"
    command: ['node', 'show', '-fields', 'node,health,uptime,model']
    privilege: 'admin'
    return_dict: true
