---

-
  name: CLI
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap
    
  tasks:
  
  - name: run ontap rest cli command
    netapp.ontap.na_ontap_rest_cli:
    command: 'vserver/services/access-check/authentication/get-dc-info'  
    verb: 'POST'
    body: {vserver: "{{ vserver_name }}"}
    <<: *login
    register: result_cifs_check_access
