---

- name: CLI
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       192.168.77.140
      username:       admin
      password:       Netapp1!
      https:          true
      validate_certs: false
    
  tasks:
  
   - name: run ontap rest cli command
     na_ontap_rest_cli:
     hostname:       "{{ PRI_CLU }}"
     username:       "{{ PRI_CLU_USER }}"
     password:       "{{ PRI_CLU_PASS }}"
     command: 'version'
     verb: 'GET'
