---

-
  name: CLI
  gather_facts: false
  hosts: localhost
  collections:
    - netapp.ontap
    
  tasks:

- name: run ontap rest cli command
  netapp.ontap.na_ontap_rest_cli:
    hostname: "192.168.77."
    username: "{{ admin username }}"
    password: "{{ admin password }}"
    command: 'version'
    verb: 'GET'
