-
  name: Ontap REST API
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.ontap
  vars:
    login: &login
      hostname: 192.168.77.140
      username: admin
      password: Netapp1!
      #hostname: "{{ admin_ip }}"
      #username: "{{ admin_username }}"
      #password: "{{ admin_password }}"
      https: true
      validate_certs: false
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false

  tasks:
   - name: run ontap REST API command as cluster admin
     na_ontap_restit:
        <<: *login
        api: cluster/software
        query:
          fields: version
     register: result
   - debug: var=result
   - assert: { that: result.status_code==200, quiet: True }
   
   
   - name: run ontap REST API command as cluster admin
     na_ontap_restit:
        <<: *login
        api: security/accounts
        query:
          fields: 'security login show'
     register: result
   - debug: var=result
   - assert: { that: result.status_code==200, quiet: True }
   
   
   - name: 'https://<mgmt-ip>/api/security/accounts'
     url: 'https://192.168.77.140/api/security/accounts'
     method: POST
     body: '{"name":"cluster_user1","applications":[{"application":"ssh","authentication_methods":["password"],"second_authentication_method":"none"},{"application":"http","authentication_methods":["password"]}],"role":"admin","password":"p@ssw@rd123"}'
     headers:
     Content-Type: application/x-www-form-urlencoded
     url_username: admin
     url_password: Netapp1!
     validate_certs: false
     register: result
