-
  name: Ontap REST API
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    admin_ip: 192.168.77.140
    admin_username: admin
    admin_password: Netapp1!
    svm_name: cifs

    login: &login
      hostname: "{{ admin_ip }}"
      username: "{{ admin_username }}"
      password: "{{ admin_password }}"
      https: true
      validate_certs: false
      feature_flags:
        trace_apis: true

  tasks:
    - name: run ontap REST API command as cluster admin - get version
      na_ontap_restit:
        <<: *login
        api: cluster/software
        query:
          fields: version
      register: result
    - debug:
         var: result.json.value
    - assert: {that: result.status_code==200, quiet: true}
