-
  name: Ontap REST API
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.ontap
  vars:
    login: &login
      #hostname: 192.168.20.140
      hostname: 192.168.77.140
      username: admin
      password: Netapp1!
      #hostname: "{{ admin_ip }}"
      #username: "{{ admin_username }}"
      #password: "{{ admin_password }}"
      https: true
      validate_certs: false
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false

  tasks:   
   - name: run ontap REST API command as cluster admin - create cluster user
     tags: create
     na_ontap_restit:
        <<: *login
        api: security/accounts
        body:
          name: patrick
        application_dicts:
          - application: ssh
            authentication_mathods: password
            second_authentication_method: none
          - application: http
            authentication_mathods: password
        role_name: admin
        set_password: test1234
        method: POST
        wait_for_completion: true
        #register: result
   - assert: {that: result.response.job_response=='success', quiet: true}
