-
  name: Ontap REST API
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    admin_ip: 192.168.77.140
    admin_username: admin
    admin_password: Netapp1!
    svm_name: cifs

    login: &login
      hostname: "{{ admin_ip }}"
      username: "{{ admin_username }}"
      password: "{{ admin_password }}"
      https: true
      validate_certs: false
      feature_flags:
        trace_apis: true

  tasks:

    - name: run ontap REST API command as cluster admin - Create ONTAP User
      tags: create
      na_ontap_restit:
        <<: *login
        api: cluster/software
        query:  # query based DELETE does not require a UUID
          name: deleteme_ln1
          svm.name: "{{ svm_name }}"
        body:
          name: deleteme_ln2
        method: PATCH
        wait_for_completion: true
      register: result
