-
  name: Ontap REST API
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    admin_ip: 192.168.77.140
    admin_username: admin
    admin_password: Netapp1!
    svm_name: cifs

    login: &login
      hostname: "{{ admin_ip }}"
      username: "{{ admin_username }}"
      password: "{{ admin_password }}"
      https: true
      validate_certs: false
      feature_flags:
        trace_apis: true
  tasks:
    - name: run ontap REST API command as cluster admin - get version
      na_ontap_restit:
        <<: *login
        api: cluster/software
        query:
          fields: version
      register: result
    - assert: {that: result.status_code==200, quiet: true}

    - name: run ontap REST API command as cluster admin - get list of SVMs
      na_ontap_restit:
        <<: *login
        api: svm/svms
      register: result
    - assert: {that: result.status_code==200, quiet: true}

    - name: run ontap REST API command as cluster admin - get list of aggregates for this SVM
      na_ontap_restit:
        <<: *login
        api: svm/svms
        query:
          fields: aggregates,cifs,nfs,uuid
          query_fields: name
          query: "{{ svm_name }}"
        hal_linking: true
      register: result


    - name: run ontap REST API command as cluster admin - patch volume (rename)
      tags: create
      na_ontap_restit:
        <<: *login
        api: storage/volumes
        query:  # query based DELETE does not require a UUID
          name: cifs_data
          svm.name: "{{ svm_name }}"
        body:
          name: cifs_data_new
        method: PATCH
        wait_for_completion: true
      register: result
