-
  name: Ontap REST API
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.ontap
  vars:
    login: &login
      #hostname: 192.168.20.140
      hostname: 192.168.77.140
      username: admin
      password: Netapp1!
      #hostname: "{{ admin_ip }}"
      #username: "{{ admin_username }}"
      #password: "{{ admin_password }}"
      https: true
      validate_certs: false
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false

  tasks:   
   - name: run ontap REST API command as cluster admin - modify volume
     tags: create
     na_ontap_restit:
        <<: *login
        api: storage/volumes
        query: # query based DELETE does not require a UUID
          name: testvol1
          svm.name: cifs
        body:
          comment: This is a Test volume
          size: 40mb
        method: PATCH
        wait_for_completion: true
        #register: result
   - assert: {that: result.response.job_response=='success', quiet: true}
