-
  name: Ontap REST API
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.ontap
  vars:
    login: &login
      state: absent
      #hostname: 192.168.20.140
      hostname: 192.168.77.140
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false

  tasks:   
   - name: Delete FlexVol
     na_ontap_volume:
        use_rest: always
        <<: *login
        name: "{{ item }}"
        aggregate_name: aggr0_data
        vserver: cifs
        wait_for_completion: True
     loop:
        - testflexvol1
        - testflexvol2
        - testflexvol3
