-
  name: Ontap REST API
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.ontap
  vars:
    login: &login
      state: present
      #hostname: 192.168.20.140
      hostname: 192.168.77.140
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    svm_login: &svm_login
      hostname: "{{ svm_admin_ip }}"
      username: "{{ svm_admin_username }}"
      password: "{{ svm_admin_password }}"
      https: true
      validate_certs: false

  tasks:   
   - name: Create FlexVol
   - volume:
       volume_name: "{{ volume.volume_name }}"
     with_items:
       - { volume_name: testflexvol1 }
       - { volume_name: testflexvol2 }
       - { volume_name: testflexvol3 }
     loop_control:
       loop_var: volume
     na_ontap_volume:
        use_rest: always
        <<: *login
        #name: testflexvol1
        is_infinite: False
        aggregate_name: aggr0_data
        size: 30
        size_unit: mb
        type: rw
        user_id: 1001
        group_id: 2002
        tiering_policy: auto
        export_policy: default
        percent_snapshot_space: 60
        #qos_policy_group: max_performance_gold
        vserver: cifs
        wait_for_completion: True
        #space_slo: none
        #nvfail_enabled: False
        comment: ansible created volume
